spring:
  profiles:
    active: ${ENV:dev}
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: vanhien27031988@gmail.com
    password: ${GMAIL_SMTP_PASS}
    properties:
      mail:
        # noinspection undefined
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO
server:
  servlet:
    context-path: /api
