spring:
  profiles:
    active: ${ENV:dev}
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
logging:
  level:
    root: INFO
server:
  servlet:
    context-path: /api
